<div class="page-header">
    <h1>Congratulations!</h1>
</div>



<div class="page-header">
    <h1>
       Post 
    </h1>
</div>

<?php

/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="next"><?php echo $this->tag->linkTo(["post/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
   
</div>
<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>Title</th>
            <th>Body</th>
          
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php 

        foreach ($posts as $post) { ?> 
<tr> 
   <td><?php echo $this->tag->linkTo(["post/edit/" . $post->id, "Edit"]); ?></td>           
  <td>
    <?php echo $post->id; ?></td> 
    <td><?php echo $post->title; ?>
    </td> <td><?php echo $post->body; ?></td> 
    <td><?php echo $this->tag->linkTo(["post/delete/" . $post->id, "Delete"]); ?></td>
</tr> <?php 
    } ?>
        </tbody>
    </table>



</div>
  
</div>
